name: workflow.yml
on:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print test.txt
        shell: bash
        run: cat ./test.txt